### ISSUE TITLE
Could you add a license?

### ISSUE THREAD

**Issue by bramvanginneken** [lfz/DSB2017#133]
If I understand correctly, this is the repo with which you won the Kaggle DSB 2017 and therefore it must be open source. Could you add a LICENSE.md file that would confirm this repo is open-course software?

**Comment by cjacobs1** [comment]
Dear authors, could you please apply a license to this repository?

Wiithout a proper license, use of this repository by the community is problematic. 

See the section on https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

I quote this website: "However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license."

**Comment by lfz** [comment]
thank you for the kind remind, I have added a MIT license

**Comment by cjacobs1** [comment]
Thanks a lot!
