### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8c  in position 16: ordinal not in range(128)

### ISSUE THREAD

**Issue by chenjing8023** [lfz/DSB2017#14]
When I run the mian.py at DSB2017-master directory, I got this error. It happened when I load the classifier.ckpt. The classifier.ckpt is downloaded from this github.  
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    checkpoint = torch.load(config_submit['classifier_param'])
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 229, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 377, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8c in position 16: ordinal not in range(128)
checkpoint = torch.load(config_submit['classifier_param'])
How can resolve it ?

**Comment by theVmagnificient** [comment]
How did you solve this problem? I ran in the same one.

**Comment by Karna4621** [comment]
I ran in the same one.Looking for solution
