### ISSUE TITLE
Initialize weights?

### ISSUE THREAD

**Issue by Kongsea** [lfz/DSB2017#17]
It seems this project uses the default weight initialization method. But as I know, sometimes weight initialization plays a very important role, so how to initialize the model parameters?
I have learned some methods to initialize simple models, but it's not easy to initialize this model since it contains many PostRes models.

**Comment by lfz** [comment]
sorry for this late reply, I haven't studied the influence of initializing weight, and I do not know how to specify a initialization method, you may refer to pytorch document for more help
