### ISSUE TITLE
Why dsb's data have coord?

### ISSUE THREAD

**Issue by Bonsen** [lfz/DSB2017#2]
in detector/labels/label_qualified.csv  
I see 008464bb8521d09a42985dd8add3d0d2   coordx1    coordx2    coordx3    diameter
Isn't the label of  008464bb8521d09a42985dd8add3d0d2 just 1 or 0 ?

**Comment by lfz** [comment]
This is the nodule location labeled by us

**Comment by Bonsen** [comment]
@lfz THANKS.
