### ISSUE TITLE
What does the loss layer mean?

### ISSUE THREAD

**Issue by iridescent303** [lfz/DSB2017#28]
Could you please tell me some details?

**Comment by lfz** [comment]
Hi, please refer to the document and faster-rcnn paper for more detail

briefly, it contains 
1. classification loss, for nodule detection
2. bounding box regression for nodule detection

3. classification loss, for cancer classification
4. miss loss, for cancer classification

**Comment by iridescent303** [comment]
OK，I will read the paper. Thank you very much.
