### ISSUE TITLE
Can I use the reposity to process the LIDC-IDRI dataset?

### ISSUE THREAD

**Issue by wentaozhu** [lfz/DSB2017#37]
Hi LFZ,

It seems the LIDC-IDRI has the same format as the kaggle dataset. Do you think the usage has some problems such as annotation difference, data format difference according to your expertise on the medical imaging processing?

Thanks a lot!
Wentao

**Comment by lfz** [comment]
I haven't tried that, but it should work

But you should be careful, because the preprocessing step is not optimized, it might be very very slow in some cases
