### ISSUE TITLE
sitk.ReadImage(filename) is broken.

### ISSUE THREAD

**Issue by Bonsen** [lfz/DSB2017#4]
in prepare.py:
if __name__=='__main__':
    full_prep(step1=True,step2=True)  is ok.
    prepare_luna()  is ok.

When it ran preprocess_luna(),
line  199:    Mask,origin,spacing,isflip = load_itk_image(os.path.join(luna_segment,name+'.mhd'))

in  load_itk_image(),
line 61:     itkimage = sitk.ReadImage(filename)

I get:
starting preprocessing luna
MetaImage: Read: Cannot open data file
Traceback (most recent call last):
  File "prepare.py", line 377, in <module>
    preprocess_luna()
  File "prepare.py", line 286, in preprocess_luna
    _=pool.map(partial_savenpy_luna,range(1))
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
RuntimeError: Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK-build/ITK/Modules/IO/Meta/src/itkMetaImageIO.cxx:483:
itk::ERROR: MetaImageIO(0x6df4d60): File cannot be read: 
/luna16/data/original_lung_masks/734.mhd for reading.
Reason: Success

**Comment by Bonsen** [comment]
I set the config wrong...

**Comment by GaoShanwen** [comment]
@Bonsen I find the only difference with you is the file in luna_segment's folder,I have not the file named ",zraw",
Can you tell me where the file created?
this is what you write in the #5
      'luna_segment':'/home/luna16/seg-lungs-LUNA16/',    ///like:
// inflating: 1.3.6.1.4.1.14519.5.2.1.6279.6001.162845309248822193437735868939.mhd
// inflating: 1.3.6.1.4.1.14519.5.2.1.6279.6001.162845309248822193437735868939.zraw

**Comment by GaoShanwen** [comment]
ok，thank you ,I slove this problem by copying .raw file,and rename it.
