### ISSUE TITLE
LabelMapping error

### ISSUE THREAD

**Issue by aguang1201** [lfz/DSB2017#70]
I modified the source in python3.6.when run detector/main.py,flow errors accur:
File "/home/panotech/PycharmProjects/DSB2017/training/detector/data.py", line 277, in __call__
    assert (input_size[i] % stride == 0)
It's assert error.I don't know why input_size[i] % stride != 0.
Would I delete the assert,or modified it like :
output_size.append(int(input_size[i] / stride))
Thank you.

**Comment by lleewwiiss** [comment]
Try ensuring that your label files are in the same order on path as your img files, you may have labels assigned to the wrong images.

**Comment by aguang1201** [comment]
@lleewwiiss 
Thank you.I will try it.

**Comment by Se1f0** [comment]
I got the same issue , how did u fix it @aguang1201  ?
