### ISSUE TITLE
stage2 data wanted

### ISSUE THREAD

**Issue by mystao** [lfz/DSB2017#80]
hi,there.
I am a AI amateur，very interesting this CT model，I can only download raw zip data .but what is stage1 and stage2 data? .I want have a test  , Is anybody can list stage1、stage2 data contents   ,   and share a stage2 data url  ?  email to mystao@163.com  will be appreciated。thx again

**Comment by bundelesneha05** [comment]
Actually stage1 and stage2 data was available on the DSB2017 site. But now it is removed from that site.

**Comment by mystao** [comment]
thanks for your reply.I see ,so  can you list which file is inclulded in stage2.zip ,maybe It's helpful for  me to understand the model and code

**Comment by mystao** [comment]
Thank you all. I have receive a usable url .

**Comment by fordavinci** [comment]
Could somebody send me one copy? Thanks  a lot! Email: 290587632@qq.com

**Comment by zp678** [comment]
Could somebody send me one copy? Thanks a lot! Email: tianzepei0636@gmail.com。@mystao@abbyQu

**Comment by holymeng** [comment]
Could somebody send me one copy? Thanks a lot! Email: holymeng@126.com。@mystao@abbyQu

**Comment by nishat0403** [comment]
@abbyQy it would be really really helpful if you share a copy at nishatsayyed26@gmail.com
Please it is very important. I am researching on this, thats why.
Thank you.

**Comment by wushuo1997** [comment]
@mystao Could you send the stage2 dataset to me?Thank you a lot!!844517964@qq.com

**Comment by wushuo1997** [comment]
@abbyQu could you send me the stage2 dataset or give me an address to download it 
? thanks a lot! Im in a hurry now ~~ thank you again. 844517964@qq.com
