### ISSUE TITLE
How to determine the value of baseline in CaseNet ?

### ISSUE THREAD

**Issue by hsinming** [lfz/DSB2017#84]
In line 82 of 'DSB2017/training/classifier/net_classifier_3.py', each nodule's malignancy is adjusted by a baseline, which is set to sigmoid(-30). Could you please explain how to determine this parameter ?

**Comment by Ricardo-Zhang** [comment]
I believe this parameter is learnable. This is just an initialization for the leaky probability.

**Comment by hsinming** [comment]
Thanks
