### ISSUE TITLE
我不清楚数据预处理这段理解对不对？

### ISSUE THREAD

**Issue by mjiansun** [lfz/DSB2017#9]
你好，lfz。我不知道你们对数据预处理具体怎么做的，下面是我的理解，不知道和你们理解的一不一样。如果不一样望指出区别！
原文：
All data are resized to 1x1x1 mm, the luminance is clipped between -1200 and 600, scaled to 0-255 and converted to uint8. A mask that include the lungs is calculated, luminance of every pixel outside the mask is set to 170.
（1）将体素转变为1x1x1
（2）保留原图像上-1200到600区间内的亮度值，将小于-1200的值全都变成-1200，大于600的值全都变成600？
（3）然后将图像的体素值同比放缩到0-255，然后使用uint8将体素中的小数转成整数
（4）找出肺部区域，最后对肺部之外的体素值全都设为170

**Comment by lfz** [comment]
是的
