### ISSUE TITLE
luna_raw的路径问题

### ISSUE THREAD

**Issue by Carl-Lei** [lfz/DSB2017#92]
我下载的luna数据里面怎么没有raw文件夹啊，只有subset0~subset9和seg-lungs-LUNA16，
 'luna_raw':'/work/DataBowl3/luna/raw/',指的是哪个文件啊

**Comment by lfz** [comment]
是所有subset的合集

**Comment by DaLei001** [comment]
LUNA16的数据集需要参赛人员才能下载，我之前没有参赛要怎么样才能下载这个数据集呢

**Comment by lihaossu** [comment]
@Carl-Lei 您好，'luna_segment':'/work/DataBowl3/luna/seg-lungs-LUNA16/'这个路径是怎么回事？
